#!/usr/bin/env tsx
/**
 * Generate RSS feed, sitemap, and robots.txt from precompiled blog manifest
 *
 * This script reads from the manifest generated by precompile-mdx.ts,
 * ensuring a single source of truth for blog metadata.
 */

import fs from 'fs';
import path from 'path';
import type { BlogFrontmatter } from '../src/content/blog/schema.js';

const BASE_URL = 'https://dylanbochman.com';
const SITE_NAME = 'Dylan Bochman';
const SITE_DESCRIPTION = 'Articles and insights on Site Reliability Engineering, Incident Management, DevOps, and System Reliability.';

interface ManifestEntry {
  file: string;
  frontmatter: BlogFrontmatter;
  readingTime: string;
}

interface Manifest {
  [slug: string]: ManifestEntry;
}

interface BlogPostForFeed {
  slug: string;
  title: string;
  description: string;
  date: string;
  updated?: string;
  author: string;
  tags: string[];
}

/**
 * Load blog posts from the precompiled manifest
 */
function loadBlogPosts(): BlogPostForFeed[] {
  const manifestPath = path.join(process.cwd(), 'src/generated/blog/manifest.json');

  if (!fs.existsSync(manifestPath)) {
    console.error('❌ Manifest not found at', manifestPath);
    console.error('   Run "npm run precompile-mdx" first');
    process.exit(1);
  }

  // Read JSON manifest directly (no brittle regex parsing)
  const manifest: Manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

  const posts: BlogPostForFeed[] = Object.entries(manifest)
    .filter(([, entry]) => !entry.frontmatter.draft)
    .map(([filenameSlug, entry]) => ({
      // Use frontmatter slug if set, otherwise use filename slug
      slug: entry.frontmatter.slug ?? filenameSlug,
      title: entry.frontmatter.title,
      description: entry.frontmatter.description,
      date: entry.frontmatter.date,
      updated: entry.frontmatter.updated,
      author: entry.frontmatter.author,
      tags: entry.frontmatter.tags || [],
    }));

  // Sort by date, newest first
  return posts.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

/**
 * Format date to ISO 8601 (YYYY-MM-DD) for sitemap compatibility
 */
function formatDateISO(date: string | undefined): string | null {
  if (!date) return null;
  const d = new Date(date);
  return d.toISOString().split('T')[0];
}

/**
 * Escape XML special characters
 */
function escapeXml(str: string): string {
  if (!str) return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Generate RSS 2.0 feed
 */
function generateRssFeed(posts: BlogPostForFeed[]): string {
  const lastBuildDate = posts.length > 0
    ? new Date(posts[0].date).toUTCString()
    : new Date().toUTCString();

  const items = posts.map(post => `    <item>
      <title>${escapeXml(post.title)}</title>
      <link>${BASE_URL}/blog/${post.slug}</link>
      <guid isPermaLink="true">${BASE_URL}/blog/${post.slug}</guid>
      <description>${escapeXml(post.description)}</description>
      <pubDate>${new Date(post.date).toUTCString()}</pubDate>
      <author>dylan@dylanbochman.com (${escapeXml(post.author)})</author>
      ${post.tags.map(tag => `<category>${escapeXml(tag)}</category>`).join('\n      ')}
    </item>`).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>${escapeXml(SITE_NAME)} - Blog</title>
    <link>${BASE_URL}/blog</link>
    <description>${escapeXml(SITE_DESCRIPTION)}</description>
    <language>en-us</language>
    <lastBuildDate>${lastBuildDate}</lastBuildDate>
    <atom:link href="${BASE_URL}/rss.xml" rel="self" type="application/rss+xml"/>
    <image>
      <url>${BASE_URL}/social-preview.png</url>
      <title>${escapeXml(SITE_NAME)} - Blog</title>
      <link>${BASE_URL}/blog</link>
    </image>
${items}
  </channel>
</rss>`;
}

/**
 * Generate sitemap XML including blog posts
 */
function generateSitemap(posts: BlogPostForFeed[]): string {
  const currentDate = new Date().toISOString().split('T')[0];

  // Static routes
  const staticRoutes = [
    { url: '/', changefreq: 'monthly', priority: '1.0' },
    { url: '/blog', changefreq: 'weekly', priority: '0.9' },
    { url: '/projects', changefreq: 'weekly', priority: '0.8' },
  ];

  // Blog post routes
  const blogRoutes = posts.map(post => ({
    url: `/blog/${post.slug}`,
    lastmod: formatDateISO(post.updated || post.date),
    changefreq: 'monthly',
    priority: '0.7',
  }));

  const allRoutes = [...staticRoutes, ...blogRoutes];

  const urls = allRoutes.map(route => `  <url>
    <loc>${BASE_URL}${route.url}</loc>
    <lastmod>${route.lastmod || currentDate}</lastmod>
    <changefreq>${route.changefreq}</changefreq>
    <priority>${route.priority}</priority>
  </url>`).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>`;
}

/**
 * Generate robots.txt with sitemap and RSS references
 */
function generateRobotsTxt(): string {
  return `User-agent: *
Allow: /

Sitemap: ${BASE_URL}/sitemap.xml
`;
}

/**
 * Main execution
 */
function main(): void {
  console.log('🔄 Loading blog posts from manifest...');
  const posts = loadBlogPosts();
  console.log(`📝 Found ${posts.length} published blog posts`);

  const publicDir = path.join(process.cwd(), 'public');

  // Generate RSS feed
  const rssFeed = generateRssFeed(posts);
  const rssPath = path.join(publicDir, 'rss.xml');
  fs.writeFileSync(rssPath, rssFeed, 'utf8');
  console.log('✅ RSS feed generated at public/rss.xml');

  // Generate sitemap
  const sitemap = generateSitemap(posts);
  const sitemapPath = path.join(publicDir, 'sitemap.xml');
  fs.writeFileSync(sitemapPath, sitemap, 'utf8');
  console.log('✅ Sitemap generated at public/sitemap.xml');

  // Generate robots.txt
  const robotsTxt = generateRobotsTxt();
  const robotsPath = path.join(publicDir, 'robots.txt');
  fs.writeFileSync(robotsPath, robotsTxt, 'utf8');
  console.log('✅ Robots.txt updated at public/robots.txt');

  console.log('\n📊 Summary:');
  console.log(`   - ${posts.length} blog posts in RSS feed`);
  console.log(`   - ${posts.length + 3} URLs in sitemap (${posts.length} posts + 3 static pages)`);
}

main();
